default: &default
  adapter: postgresql
  encoding: unicode
  timeout: 5000
  username: dev
  password: 282414Rr
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: shop_development

test:
  <<: *default
  database: shop_test

production:
  <<: *default
  database: shop_production
  username: dev
  password: <%= ENV['SHOP_DATABASE_PASSWORD'] %>
